/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.usuarios;

/**
 *
 * @author luish
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form UsuariosVista
     */
    public Usuarios() {
        initComponents();
        inicializarSubpaneles();
    }

    private void inicializarSubpaneles() {
        removeAll();

        // ===================== SubPanelLogin1 =====================
        SubPanelUsuarios1 = new vista.usuarios.SubPanelUsuarios1(); // 
        setLayout(new java.awt.BorderLayout());
        add(SubPanelUsuarios1, java.awt.BorderLayout.CENTER);

        // Refrescar layout
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanelUsuarios1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout SubPanelUsuarios1Layout = new javax.swing.GroupLayout(SubPanelUsuarios1);
        SubPanelUsuarios1.setLayout(SubPanelUsuarios1Layout);
        SubPanelUsuarios1Layout.setHorizontalGroup(
            SubPanelUsuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SubPanelUsuarios1Layout.setVerticalGroup(
            SubPanelUsuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(SubPanelUsuarios1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubPanelUsuarios1;
    // End of variables declaration//GEN-END:variables
}
