package vista.dashboard;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import recursos.fonts.FontLoader;
import recursos.temas.ProFitDarkTheme;
import vista.login.Login;


/**
 *
 * @author luish
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        inicializarSubpaneles();
    }
    
    public static JFrame frame;

    public static void main(String[] args) {
        try {
            FontLoader.registerPoppins();
            ProFitDarkTheme.setup();
        } catch (Exception e) {
            System.err.println("Error al aplicar tema o fuentes: " + e.getMessage());
        }

        SwingUtilities.invokeLater(() -> {
            frame = new JFrame("ProFit - Sistema de Suplementos");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setResizable(false);
            frame.setSize(1000, 500);
            frame.setLocationRelativeTo(null);
            frame.setContentPane(new Dashboard());
            frame.setVisible(true);
        });
    }

    private void inicializarSubpaneles() {
        removeAll();

        // ===================== SubPanelLogin1 =====================
        SubPanelDashboard1 = new vista.dashboard.SubPanelDashboard1();
        setLayout(new java.awt.BorderLayout());
        add(SubPanelDashboard1, java.awt.BorderLayout.CENTER);

        // Refrescar layout
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanelDashboard1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout SubPanelDashboard1Layout = new javax.swing.GroupLayout(SubPanelDashboard1);
        SubPanelDashboard1.setLayout(SubPanelDashboard1Layout);
        SubPanelDashboard1Layout.setHorizontalGroup(
            SubPanelDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SubPanelDashboard1Layout.setVerticalGroup(
            SubPanelDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(SubPanelDashboard1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubPanelDashboard1;
    // End of variables declaration//GEN-END:variables
}
