package vista.dashboard;

import javax.swing.border.EmptyBorder;

/**
 *
 * @author Luis Angel Hernandez
 */
public class SubPanelDashboard1 extends javax.swing.JPanel {

    /**
     * Creates new form SubPanelDashboard1
     */
    public SubPanelDashboard1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMain = new javax.swing.JPanel();
        jPnlTiitle = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jPnlGestionUsuarios = new javax.swing.JPanel();
        jBtnGestionUsuarios = new javax.swing.JButton();
        jPnlGestionProductos = new javax.swing.JPanel();
        jBtnGestionProductos = new javax.swing.JButton();
        jPnlGestionCategorias = new javax.swing.JPanel();
        jBtnGestionCategorias = new javax.swing.JButton();
        jPnlCerrarSesion = new javax.swing.JPanel();
        jBtnCerrarSesion = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 1));

        jPnlMain.setLayout(new java.awt.GridLayout(5, 1, 0, 25));
        jPnlMain.setBorder(new EmptyBorder(20,300,20,300));

        jPnlTiitle.setLayout(new java.awt.GridLayout(1, 1));

        jLblTitle.setText("Dashboard Profit");
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlTiitle.add(jLblTitle);

        jPnlMain.add(jPnlTiitle);

        jPnlGestionUsuarios.setLayout(new java.awt.GridLayout(1, 1));

        jBtnGestionUsuarios.setText("Gestion de usuarios");
        jBtnGestionUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGestionUsuariosMouseClicked(evt);
            }
        });
        jPnlGestionUsuarios.add(jBtnGestionUsuarios);

        jPnlMain.add(jPnlGestionUsuarios);

        jPnlGestionProductos.setLayout(new java.awt.GridLayout(1, 1));

        jBtnGestionProductos.setText("Gestion de productos");
        jBtnGestionProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnGestionProductosMouseClicked(evt);
            }
        });
        jPnlGestionProductos.add(jBtnGestionProductos);

        jPnlMain.add(jPnlGestionProductos);

        jPnlGestionCategorias.setLayout(new java.awt.GridLayout(1, 1));

        jBtnGestionCategorias.setText("Gestion de categorias");
        jBtnGestionCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGestionCategoriasActionPerformed(evt);
            }
        });
        jPnlGestionCategorias.add(jBtnGestionCategorias);

        jPnlMain.add(jPnlGestionCategorias);

        jPnlCerrarSesion.setLayout(new java.awt.GridLayout(1, 1));

        jBtnCerrarSesion.setText("Cerrar sesión");
        jPnlCerrarSesion.add(jBtnCerrarSesion);

        jPnlMain.add(jPnlCerrarSesion);

        add(jPnlMain);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGestionUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGestionUsuariosMouseClicked
        // TODO add your handling code here:
        app.Main.frame.setContentPane(new vista.usuarios.Usuarios());
        app.Main.frame.revalidate();
        app.Main.frame.repaint();
    }//GEN-LAST:event_jBtnGestionUsuariosMouseClicked

    private void jBtnGestionProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGestionProductosMouseClicked
        // TODO add your handling code here:
        app.Main.frame.setContentPane(new vista.productos.Productos());
        app.Main.frame.revalidate();
        app.Main.frame.repaint();
    }//GEN-LAST:event_jBtnGestionProductosMouseClicked

    private void jBtnGestionCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGestionCategoriasActionPerformed
        // TODO add your handling code here:
        app.Main.frame.setContentPane(new vista.categorias.Categorias());
        app.Main.frame.revalidate();
        app.Main.frame.repaint();

//        vista.dashboard.Dashboard.frame.setContentPane(new vista.categorias.Categorias());
//        vista.dashboard.Dashboard.frame.revalidate();
//        vista.dashboard.Dashboard.frame.repaint();
    }//GEN-LAST:event_jBtnGestionCategoriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCerrarSesion;
    private javax.swing.JButton jBtnGestionCategorias;
    private javax.swing.JButton jBtnGestionProductos;
    private javax.swing.JButton jBtnGestionUsuarios;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPnlCerrarSesion;
    private javax.swing.JPanel jPnlGestionCategorias;
    private javax.swing.JPanel jPnlGestionProductos;
    private javax.swing.JPanel jPnlGestionUsuarios;
    private javax.swing.JPanel jPnlMain;
    private javax.swing.JPanel jPnlTiitle;
    // End of variables declaration//GEN-END:variables
}
