/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.login;

/**
 *
 * @author luish
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        inicializarSubpaneles();
    }

    private void inicializarSubpaneles() {
        removeAll();

        // ===================== SubPanelLogin1 =====================
        SubPanelLogin1 = new vista.login.SubPanelLogin1();
        setLayout(new java.awt.BorderLayout());
        add(SubPanelLogin1, java.awt.BorderLayout.CENTER);

        // Refrescar layout
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanelLogin1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout SubPanelLogin1Layout = new javax.swing.GroupLayout(SubPanelLogin1);
        SubPanelLogin1.setLayout(SubPanelLogin1Layout);
        SubPanelLogin1Layout.setHorizontalGroup(
            SubPanelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SubPanelLogin1Layout.setVerticalGroup(
            SubPanelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(SubPanelLogin1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubPanelLogin1;
    // End of variables declaration//GEN-END:variables
}
