package vista.login;

import controlador.UsuarioControlador;
import java.awt.Color;
import javax.swing.UIManager;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author luish
 */
public class SubPanelLogin1 extends javax.swing.JPanel {

    /**
     * Creates new form SubPanelVista1
     */
    public SubPanelLogin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlIzuiqerda = new javax.swing.JPanel();
        jPnlTitle = new javax.swing.JPanel();
        jLblTittle = new javax.swing.JLabel();
        jPnlRegisterButton = new javax.swing.JPanel();
        jLblTxt = new javax.swing.JLabel();
        jLblLink = new javax.swing.JLabel();
        jPnlEmail = new javax.swing.JPanel(){

            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Fondo del tema
                Color bg = (Color) UIManager.get("SubPanel.background");
                g2.setColor(bg);

                // Fondo redondeado
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);

                g2.dispose();
                super.paintComponent(g);
            }

        };
        jLblEmail = new javax.swing.JLabel();
        jPnlInternoEmail = new javax.swing.JPanel();
        jLblIconEmail = new javax.swing.JLabel();
        jPnlPassword = new javax.swing.JPanel(){

            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Fondo del tema
                Color bg = (Color) UIManager.get("SubPanel.background");
                g2.setColor(bg);

                // Fondo redondeado
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);

                g2.dispose();
                super.paintComponent(g);
            }

        };
        jLblPassword = new javax.swing.JLabel();
        jPnlInternoPassword = new javax.swing.JPanel();
        jPasswordField = new javax.swing.JPasswordField();
        jLblIconPassword = new javax.swing.JLabel();
        jPnlLoginButton1 = new javax.swing.JPanel();
        jBtnCrearCuenta = new recursos.ui.IndividualButton("Iniciar Sesión")
        ;
        jPnlDerecha = new javax.swing.JPanel();
        jLblBackgroundImage = new recursos.ui.ScaledImageLabel() ;

        setPreferredSize(new java.awt.Dimension(1000, 500));
        setLayout(new java.awt.GridLayout(1, 2));

        jPnlIzuiqerda.setLayout(new java.awt.GridLayout(5, 1, 0, 40));
        jPnlIzuiqerda.setBorder(new EmptyBorder(8,12,8,12));

        jPnlTitle.setLayout(new java.awt.GridLayout(1, 1));

        jLblTittle.setText("Iniciar Sesión");
        jLblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTittle.putClientProperty("FlatLaf.styleClass", "h1");
        jPnlTitle.add(jLblTittle);

        jPnlIzuiqerda.add(jPnlTitle);

        jPnlRegisterButton.setLayout(new java.awt.GridLayout(1, 2, 8, 0));

        jLblTxt.setText("¿No tienes cuenta?");
        jLblTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPnlRegisterButton.add(jLblTxt);

        jLblLink.setText("Registrar Cuenta");
        jLblLink.setForeground((Color) UIManager.get("LabelValor.foreground"));
        jLblLink.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblLinkMouseClicked(evt);
            }
        });
        jPnlRegisterButton.add(jLblLink);

        jPnlIzuiqerda.add(jPnlRegisterButton);

        jPnlEmail.setLayout(new java.awt.GridLayout(2, 1, 0, 2));
        jPnlEmail.setBorder(new com.formdev.flatlaf.ui.FlatRoundBorder());
        jPnlEmail.setOpaque(false);

        jLblEmail.setText("Email");
        jLblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPnlEmail.add(jLblEmail);

        jPnlInternoEmail.setLayout(new java.awt.GridLayout(1, 2));
        jPnlInternoEmail.setOpaque(false);

        jTxtFEmail.setOpaque(false);
        jTxtFEmail.setBorder(new EmptyBorder(8,12,8,12));
        jPnlInternoEmail.add(jTxtFEmail);

        jLblIconEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblIconEmail.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ImageIcon emalIcon = new ImageIcon(getClass().getResource("/recursos/icons/profit_email1.png"));

        Image scaledEmail = emalIcon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);

        jLblIconEmail.setIcon(new ImageIcon(scaledEmail));
        jPnlInternoEmail.add(jLblIconEmail);

        jPnlEmail.add(jPnlInternoEmail);

        jPnlIzuiqerda.add(jPnlEmail);

        jPnlPassword.setLayout(new java.awt.GridLayout(2, 1, 0, 2));
        jPnlPassword.setBorder(new com.formdev.flatlaf.ui.FlatRoundBorder());
        jPnlPassword.setOpaque(false);

        jLblPassword.setText("Contraseña");
        jLblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPnlPassword.add(jLblPassword);

        jPnlInternoPassword.setLayout(new java.awt.GridLayout(1, 2));
        jPnlInternoPassword.setOpaque(false);

        jPasswordField.setOpaque(false);
        jPasswordField.setBorder(new EmptyBorder(8,12,8,12));
        jPnlInternoPassword.add(jPasswordField);

        jLblIconPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblIconPassword.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ImageIcon passwordIcon = new ImageIcon(getClass().getResource("/recursos/icons/profit_password1.png"));

        Image scaledPassword = passwordIcon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);

        jLblIconPassword.setIcon(new ImageIcon(scaledPassword));
        jLblIconPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblIconPasswordMousePressed(evt);
            }
        });
        jPnlInternoPassword.add(jLblIconPassword);

        jPnlPassword.add(jPnlInternoPassword);

        jPnlIzuiqerda.add(jPnlPassword);

        jPnlLoginButton1.setBorder(BorderFactory.createEmptyBorder(10, 40, 10, 40));
        jPnlLoginButton1.setLayout(new java.awt.GridLayout(1, 1));

        jBtnCrearCuenta.putClientProperty("JComponent.roundRect", true);             // activa redondeo FlatLaf
        jBtnCrearCuenta.putClientProperty("JComponent.style", "arc: 20; borderWidth: 1;"); // radio 20px, grosor 1px
        jBtnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearCuentaActionPerformed(evt);
            }
        });
        jPnlLoginButton1.add(jBtnCrearCuenta);

        jPnlIzuiqerda.add(jPnlLoginButton1);

        add(jPnlIzuiqerda);

        jPnlDerecha.setLayout(new java.awt.GridLayout(1, 1));

        ImageIcon icon = new ImageIcon(getClass().getResource("/recursos/images/profit_login_register_background.png"));
        ((recursos.ui.ScaledImageLabel) jLblBackgroundImage).setImage(icon.getImage());
        jPnlDerecha.add(jLblBackgroundImage);

        add(jPnlDerecha);
    }// </editor-fold>//GEN-END:initComponents

    private boolean passwordMostrando = false;
    private char passwordEchoOriginal;
    private boolean echoGuardado = false;

    private void jLblLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblLinkMouseClicked
        // Revaldar y repintar el JFrame al hacer clic:
        app.Main.frame.setContentPane(new vista.register.Register());
        app.Main.frame.revalidate();
        app.Main.frame.repaint();
    }//GEN-LAST:event_jLblLinkMouseClicked

    private void jLblIconPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblIconPasswordMousePressed
        // TODO add your handling code here:

        // Guardar el echo char original solo la primera vez
        if (!echoGuardado) {
            passwordEchoOriginal = jPasswordField.getEchoChar();
            echoGuardado = true;
        }

        if (!passwordMostrando) {
            // Mostrar contraseña
            jPasswordField.setEchoChar((char) 0);
            passwordMostrando = true;
        } else {
            // Restaurar contraseña oculta
            jPasswordField.setEchoChar(passwordEchoOriginal);
            passwordMostrando = false;
        }


    }//GEN-LAST:event_jLblIconPasswordMousePressed

    private void jBtnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearCuentaActionPerformed
        // TODO add your handling code here:
        String email = jTxtFEmail.getText();
        String pass = new String(jPasswordField.getPassword());

        UsuarioControlador controlador = new UsuarioControlador();

        if (controlador.login(email, pass)) {
            new Dashboard().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Email o contraseña incorrectos");
        }
    }//GEN-LAST:event_jBtnCrearCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCrearCuenta;
    private javax.swing.JLabel jLblBackgroundImage;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblIconEmail;
    private javax.swing.JLabel jLblIconPassword;
    private javax.swing.JLabel jLblLink;
    private javax.swing.JLabel jLblPassword;
    private javax.swing.JLabel jLblTittle;
    private javax.swing.JLabel jLblTxt;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPanel jPnlDerecha;
    private javax.swing.JPanel jPnlEmail;
    private javax.swing.JPanel jPnlInternoEmail;
    private javax.swing.JPanel jPnlInternoPassword;
    private javax.swing.JPanel jPnlIzuiqerda;
    private javax.swing.JPanel jPnlLoginButton1;
    private javax.swing.JPanel jPnlPassword;
    private javax.swing.JPanel jPnlRegisterButton;
    private javax.swing.JPanel jPnlTitle;
    private final javax.swing.JTextField jTxtFEmail = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
