/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.login;

/**
 *
 * @author luish
 */
public class SubPanelLogin1 extends javax.swing.JPanel {

    /**
     * Creates new form SubPanelVista1
     */
    public SubPanelLogin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlIzuiqerda = new javax.swing.JPanel();
        jPnlTitle = new javax.swing.JPanel();
        jLblTittle = new javax.swing.JLabel();
        jPnlRegisterButton = new javax.swing.JPanel();
        jLblTxt = new javax.swing.JLabel();
        jLblLink = new javax.swing.JLabel();
        jPnlName = new javax.swing.JPanel();
        jPnlEmail = new javax.swing.JPanel();
        jPnlPassword = new javax.swing.JPanel();
        jPnlLoginButton = new javax.swing.JPanel();
        jPnlDerecha = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 2));

        jPnlIzuiqerda.setLayout(new java.awt.GridLayout(6, 1, 0, 3));

        jPnlTitle.setLayout(new java.awt.GridLayout(1, 1));

        jLblTittle.setText("Iniciar Sesión");
        jLblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTittle.putClientProperty("FlatLaf.styleClass", "h1");
        jPnlTitle.add(jLblTittle);

        jPnlIzuiqerda.add(jPnlTitle);

        jPnlRegisterButton.setLayout(new java.awt.GridLayout(1, 2, 0, 1));

        jLblTxt.setText("¿No tienes cuenta?");
        jPnlRegisterButton.add(jLblTxt);

        jLblLink.setText("Registrar usuario");
        //jLblLink.setForeground(UI Manager.getColor("LabelValor2.foreground"));
        jPnlRegisterButton.add(jLblLink);

        jPnlIzuiqerda.add(jPnlRegisterButton);

        javax.swing.GroupLayout jPnlNameLayout = new javax.swing.GroupLayout(jPnlName);
        jPnlName.setLayout(jPnlNameLayout);
        jPnlNameLayout.setHorizontalGroup(
            jPnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPnlNameLayout.setVerticalGroup(
            jPnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPnlIzuiqerda.add(jPnlName);

        javax.swing.GroupLayout jPnlEmailLayout = new javax.swing.GroupLayout(jPnlEmail);
        jPnlEmail.setLayout(jPnlEmailLayout);
        jPnlEmailLayout.setHorizontalGroup(
            jPnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPnlEmailLayout.setVerticalGroup(
            jPnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPnlIzuiqerda.add(jPnlEmail);

        javax.swing.GroupLayout jPnlPasswordLayout = new javax.swing.GroupLayout(jPnlPassword);
        jPnlPassword.setLayout(jPnlPasswordLayout);
        jPnlPasswordLayout.setHorizontalGroup(
            jPnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPnlPasswordLayout.setVerticalGroup(
            jPnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPnlIzuiqerda.add(jPnlPassword);

        javax.swing.GroupLayout jPnlLoginButtonLayout = new javax.swing.GroupLayout(jPnlLoginButton);
        jPnlLoginButton.setLayout(jPnlLoginButtonLayout);
        jPnlLoginButtonLayout.setHorizontalGroup(
            jPnlLoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPnlLoginButtonLayout.setVerticalGroup(
            jPnlLoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPnlIzuiqerda.add(jPnlLoginButton);

        add(jPnlIzuiqerda);

        javax.swing.GroupLayout jPnlDerechaLayout = new javax.swing.GroupLayout(jPnlDerecha);
        jPnlDerecha.setLayout(jPnlDerechaLayout);
        jPnlDerechaLayout.setHorizontalGroup(
            jPnlDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPnlDerechaLayout.setVerticalGroup(
            jPnlDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(jPnlDerecha);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblLink;
    private javax.swing.JLabel jLblTittle;
    private javax.swing.JLabel jLblTxt;
    private javax.swing.JPanel jPnlDerecha;
    private javax.swing.JPanel jPnlEmail;
    private javax.swing.JPanel jPnlIzuiqerda;
    private javax.swing.JPanel jPnlLoginButton;
    private javax.swing.JPanel jPnlName;
    private javax.swing.JPanel jPnlPassword;
    private javax.swing.JPanel jPnlRegisterButton;
    private javax.swing.JPanel jPnlTitle;
    // End of variables declaration//GEN-END:variables
}
