/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.categorias;

/**
 *
 * @author Luis Angel Hernandez
 */
public class Categorias extends javax.swing.JPanel {

    /**
     * Creates new form asd
     */
    public Categorias() {
        initComponents();
        inicializarSubpaneles();
    }

    private void inicializarSubpaneles() {
        removeAll();

        // ===================== SubPanelLogin1 =====================
        SubPanelCategorias1 = new vista.categorias.SubPanelCategorias1(); // 
        setLayout(new java.awt.BorderLayout());
        add(SubPanelCategorias1, java.awt.BorderLayout.CENTER);

        // Refrescar layout
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanelCategorias1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout SubPanelCategorias1Layout = new javax.swing.GroupLayout(SubPanelCategorias1);
        SubPanelCategorias1.setLayout(SubPanelCategorias1Layout);
        SubPanelCategorias1Layout.setHorizontalGroup(
            SubPanelCategorias1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SubPanelCategorias1Layout.setVerticalGroup(
            SubPanelCategorias1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(SubPanelCategorias1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubPanelCategorias1;
    // End of variables declaration//GEN-END:variables
}
