package vista.categorias;

import java.awt.Frame;
import modelo.Categoria;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import controlador.CategoriaControlador;

/**
 *
 * @author Luis Angel Hernandez
 */
public class FormCategoria extends javax.swing.JDialog {

    private Categoria categoriaEditar;
    private SubPanelCategorias1 panelPadre;
    private CategoriaControlador controlador = new CategoriaControlador();

    public FormCategoria(modelo.Categoria categoria, boolean modal, SubPanelCategorias1 panelPadre) {
        super((Frame) null, modal);
        this.categoriaEditar = categoria;
        this.panelPadre = panelPadre;

        setTitle(categoria == null ? "Agregar Categoría" : "Editar Categoría");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setResizable(false);

        initComponents();

        if (categoria != null) {
            cargarDatos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMain = new javax.swing.JPanel();
        jPnlTitle = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jPnlNombreCategoria = new javax.swing.JPanel();
        jLblNombreCat = new javax.swing.JLabel();
        jTxFNombreCat = new javax.swing.JTextField();
        jPnlDescripcionCategoria = new javax.swing.JPanel();
        jLblDescripcionCat = new javax.swing.JLabel();
        jTxFDescripcionCat = new javax.swing.JTextField();
        jPnlGuardarButton = new javax.swing.JPanel();
        jBtnGuardar = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPnlMain.setLayout(new java.awt.GridLayout(4, 1, 0, 10));
        jPnlMain.setBorder(new EmptyBorder(8,12,8,12));

        jPnlTitle.setLayout(new java.awt.GridLayout(1, 1));

        jLblTitle.setText("Agregar Categoria");
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlTitle.add(jLblTitle);

        jPnlMain.add(jPnlTitle);

        jPnlNombreCategoria.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLblNombreCat.setText("Nombre de categoria: ");
        jLblNombreCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlNombreCategoria.add(jLblNombreCat);
        jPnlNombreCategoria.add(jTxFNombreCat);

        jPnlMain.add(jPnlNombreCategoria);

        jPnlDescripcionCategoria.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLblNombreCat.setText("Descripción: ");
        jLblDescripcionCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlDescripcionCategoria.add(jLblDescripcionCat);
        jPnlDescripcionCategoria.add(jTxFDescripcionCat);

        jPnlMain.add(jPnlDescripcionCategoria);

        jPnlGuardarButton.setLayout(new java.awt.GridLayout(1, 1));

        jBtnGuardar.addActionListener(e -> guardarCategoria());
        jBtnGuardar.setText("Guardar");
        jPnlGuardarButton.add(jBtnGuardar);

        jPnlMain.add(jPnlGuardarButton);

        getContentPane().add(jPnlMain);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos() {
        jTxFNombreCat.setText(categoriaEditar.getNombreCategoria());
        jTxFDescripcionCat.setText(categoriaEditar.getDescripcion());
    }

    private void guardarCategoria() {
        String nombre = jTxFNombreCat.getText().trim();
        String descripcion = jTxFDescripcionCat.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
            return;
        }

        // EDITAR
        if (categoriaEditar != null) {
            categoriaEditar.setNombreCategoria(nombre);
            categoriaEditar.setDescripcion(descripcion);

            if (controlador.actualizar(categoriaEditar)) {
                JOptionPane.showMessageDialog(this, "Categoría actualizada correctamente");
                panelPadre.cargarCategorias();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar categoría");
            }

            return;
        }

        // AGREGAR
        Categoria nueva = new Categoria();
        nueva.setNombreCategoria(nombre);
        nueva.setDescripcion(descripcion);

        if (controlador.agregar(nueva)) {
            JOptionPane.showMessageDialog(this, "Categoría agregada correctamente");
            panelPadre.cargarCategorias();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar categoría");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JLabel jLblDescripcionCat;
    private javax.swing.JLabel jLblNombreCat;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPnlDescripcionCategoria;
    private javax.swing.JPanel jPnlGuardarButton;
    private javax.swing.JPanel jPnlMain;
    private javax.swing.JPanel jPnlNombreCategoria;
    private javax.swing.JPanel jPnlTitle;
    private javax.swing.JTextField jTxFDescripcionCat;
    private javax.swing.JTextField jTxFNombreCat;
    // End of variables declaration//GEN-END:variables
}
