package vista.categorias;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Angel Hernandez
 */
public class SubPanelCategorias1 extends javax.swing.JPanel{

    /**
     * Creates new form SubPanelCategorias1
     */
    public SubPanelCategorias1() {
        initComponents();
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMain = new javax.swing.JPanel();
        jPnlTitle = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategorias = new javax.swing.JTable();
        jPnlButtons = new javax.swing.JPanel();
        jBtnAgregar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 1));

        jPnlMain.setLayout(new javax.swing.BoxLayout(jPnlMain, javax.swing.BoxLayout.PAGE_AXIS));

        jPnlTitle.setLayout(new java.awt.GridLayout(1, 1));
        jPnlTitle.setBorder(BorderFactory.createEmptyBorder(8, 0, 8, 0));

        jLblTitle.setText("Dashboard Categorias");
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlTitle.add(jLblTitle);

        jPnlMain.add(jPnlTitle);

        jTableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "ID", "Nombre", "Descripción" }
        ));
        jScrollPane1.setViewportView(jTableCategorias);

        jPnlMain.add(jScrollPane1);

        jPnlButtons.setLayout(new java.awt.GridLayout(1, 4, 8, 0));
        jPnlButtons.setBorder(BorderFactory.createEmptyBorder(8, 0, 8, 0));

        jBtnAgregar.setText("Agregar");

        jBtnAgregar.addActionListener(e -> {
            new FormCategoria(null, true, this).setVisible(true);
        });
        jPnlButtons.add(jBtnAgregar);

        jBtnEditar.setText("Editar");

        jBtnEditar.addActionListener(e -> {
            int fila = jTableCategorias.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione una categoría");
                return;
            }

            int id = (int) jTableCategorias.getValueAt(fila, 0);
            String nombre = (String) jTableCategorias.getValueAt(fila, 1);
            String descripcion = (String) jTableCategorias.getValueAt(fila, 2);

            modelo.Categoria c = new modelo.Categoria();
            c.setIdCategoria(id);
            c.setNombreCategoria(nombre);
            c.setDescripcion(descripcion);

            new FormCategoria(c, true, this).setVisible(true);
        });
        jPnlButtons.add(jBtnEditar);

        jBtnEliminar.setText("Eliminar");

        jBtnEliminar.addActionListener(e -> {
            int fila = jTableCategorias.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione una categoría");
                return;
            }

            int id = (int) jTableCategorias.getValueAt(fila, 0);

            int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar categoría?",
                "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                controlador.CategoriaControlador ctrl = new controlador.CategoriaControlador();
                if (ctrl.eliminar(id)) {
                    cargarCategorias();
                }
            }
        });
        jPnlButtons.add(jBtnEliminar);

        jBtnActualizar.setText("Actualizar");

        jBtnActualizar.addActionListener(e -> cargarCategorias());
        jPnlButtons.add(jBtnActualizar);

        jPnlMain.add(jPnlButtons);

        add(jPnlMain);
    }// </editor-fold>//GEN-END:initComponents

    public void cargarCategorias() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCategorias.getModel();
        modelo.setRowCount(0); // limpiar tabla

        controlador.CategoriaControlador ctrl = new controlador.CategoriaControlador();

        for (modelo.Categoria c : ctrl.listar()) {
            modelo.addRow(new Object[]{
                c.getIdCategoria(),
                c.getNombreCategoria(),
                c.getDescripcion()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizar;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPnlButtons;
    private javax.swing.JPanel jPnlMain;
    private javax.swing.JPanel jPnlTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCategorias;
    // End of variables declaration//GEN-END:variables
}
