package vista.register;

/**
 *
 * @author luish
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
        inicializarSubpaneles();
    }

    private void inicializarSubpaneles() {
        removeAll();

        // ===================== SubPanelLogin1 =====================
        SubPanelRegister1 = new vista.register.SubPanelRegister1(); // 
        setLayout(new java.awt.BorderLayout());
        add(SubPanelRegister1, java.awt.BorderLayout.CENTER);

        // Refrescar layout
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanelRegister1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout SubPanelRegister1Layout = new javax.swing.GroupLayout(SubPanelRegister1);
        SubPanelRegister1.setLayout(SubPanelRegister1Layout);
        SubPanelRegister1Layout.setHorizontalGroup(
            SubPanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SubPanelRegister1Layout.setVerticalGroup(
            SubPanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(SubPanelRegister1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubPanelRegister1;
    // End of variables declaration//GEN-END:variables
}
