package vista.productos;

import controlador.CategoriaControlador;
import controlador.ProductoControlador;
import modelo.Categoria;
import modelo.Producto;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 *
 * @author Luis Angel Hernandez
 */
public class FormProducto extends javax.swing.JDialog {

    private Producto productoEditar;
    private SubPanelProductos1 panelPadre;

    private ProductoControlador prodCtrl = new ProductoControlador();
    private CategoriaControlador catCtrl = new CategoriaControlador();

    public FormProducto(Producto producto, boolean modal, SubPanelProductos1 panelPadre) {
        super((Frame) null, modal);
        this.productoEditar = producto;
        this.panelPadre = panelPadre;

        setTitle(producto == null ? "Agregar Producto" : "Editar Producto");
        setSize(450, 450);
        setLocationRelativeTo(null);
        setResizable(false);

        initComponents();
        cargarCategorias();

        if (productoEditar != null) {
            cargarDatos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMain = new javax.swing.JPanel();
        jPnlTitle = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jPnlNombreProducto = new javax.swing.JPanel();
        jLblNombreProd = new javax.swing.JLabel();
        jTxFNombreProd = new javax.swing.JTextField();
        jPnlCategoriaProducto = new javax.swing.JPanel();
        jLblCategoriaProd = new javax.swing.JLabel();
        jCbxCategoriaProd = new javax.swing.JComboBox<>();
        jPnlPrecioProducto = new javax.swing.JPanel();
        jLblPrecioProd = new javax.swing.JLabel();
        jTxFPrecioProd = new javax.swing.JTextField();
        jPnlStockProducto = new javax.swing.JPanel();
        jLblStockProd = new javax.swing.JLabel();
        jTxFStockProd = new javax.swing.JTextField();
        jPnlDescripcionProducto = new javax.swing.JPanel();
        jLblDescripcionProd = new javax.swing.JLabel();
        jTxFDescripcionProd = new javax.swing.JTextField();
        jPnlGuardarButton = new javax.swing.JPanel();
        jBtnGuardar = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPnlMain.setLayout(new java.awt.GridLayout(7, 1, 0, 3));
        jPnlMain.setBorder(new EmptyBorder(8,12,8,12));

        jPnlTitle.setLayout(new java.awt.GridLayout(1, 1));

        jLblTitle.setText("Agregar Producto");
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlTitle.add(jLblTitle);

        jPnlMain.add(jPnlTitle);

        jPnlNombreProducto.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLblNombreProd.setText("Nombre del producto: ");
        jLblNombreProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlNombreProducto.add(jLblNombreProd);
        jPnlNombreProducto.add(jTxFNombreProd);

        jPnlMain.add(jPnlNombreProducto);

        jPnlCategoriaProducto.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLblCategoriaProd.setText("Categoria: ");
        jLblCategoriaProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlCategoriaProducto.add(jLblCategoriaProd);

        jPnlCategoriaProducto.add(jCbxCategoriaProd);

        jPnlMain.add(jPnlCategoriaProducto);

        jPnlPrecioProducto.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLblPrecioProd.setText("Precio: ");
        jLblPrecioProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlPrecioProducto.add(jLblPrecioProd);
        jPnlPrecioProducto.add(jTxFPrecioProd);

        jPnlMain.add(jPnlPrecioProducto);

        jPnlStockProducto.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLblStockProd.setText("Stock: ");
        jLblStockProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlStockProducto.add(jLblStockProd);
        jPnlStockProducto.add(jTxFStockProd);

        jPnlMain.add(jPnlStockProducto);

        jPnlDescripcionProducto.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLblDescripcionProd.setText("Descripción: ");
        jLblDescripcionProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPnlDescripcionProducto.add(jLblDescripcionProd);
        jPnlDescripcionProducto.add(jTxFDescripcionProd);

        jPnlMain.add(jPnlDescripcionProducto);

        jPnlGuardarButton.setLayout(new java.awt.GridLayout(1, 1));

        jBtnGuardar.addActionListener(e -> guardarProducto());
        jPnlGuardarButton.add(jBtnGuardar);

        jPnlMain.add(jPnlGuardarButton);

        getContentPane().add(jPnlMain);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarCategorias() {
        for (Categoria c : catCtrl.listar()) {
            jCbxCategoriaProd.addItem(c);
        }
    }

    private void cargarDatos() {
        jTxFNombreProd.setText(productoEditar.getNombreProducto());
        jTxFDescripcionProd.setText(productoEditar.getDescripcion());
        jTxFPrecioProd.setText(String.valueOf(productoEditar.getPrecio()));
        jTxFStockProd.setText(String.valueOf(productoEditar.getStock()));

        for (int i = 0; i < jCbxCategoriaProd.getItemCount(); i++) {
            if (jCbxCategoriaProd.getItemAt(i).getIdCategoria() == productoEditar.getIdCategoria()) {
                jCbxCategoriaProd.setSelectedIndex(i);
                break;
            }
        }
    }

    private void guardarProducto() {

        String nombre = jTxFNombreProd.getText().trim();
        String descripcion = jTxFDescripcionProd.getText().trim();
        String precioTxt = jTxFPrecioProd.getText().trim();
        String stockTxt = jTxFStockProd.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
            return;
        }

        double precio;
        int stock;

        try {
            precio = Double.parseDouble(precioTxt);
            stock = Integer.parseInt(stockTxt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Precio o stock inválido");
            return;
        }

        Categoria categoriaSeleccionada = (Categoria) jCbxCategoriaProd.getSelectedItem();

        if (categoriaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una categoría");
            return;
        }

       // Editar
        if (productoEditar != null) {
            productoEditar.setNombreProducto(nombre);
            productoEditar.setDescripcion(descripcion);
            productoEditar.setPrecio(precio);
            productoEditar.setStock(stock);
            productoEditar.setIdCategoria(categoriaSeleccionada.getIdCategoria());

            if (prodCtrl.actualizar(productoEditar)) {
                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente");
                panelPadre.cargarProductos();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar producto");
            }
            return;
        }

        // Agregar
        Producto nuevo = new Producto();
        nuevo.setNombreProducto(nombre);
        nuevo.setDescripcion(descripcion);
        nuevo.setPrecio(precio);
        nuevo.setStock(stock);
        nuevo.setIdCategoria(categoriaSeleccionada.getIdCategoria());

        if (prodCtrl.agregar(nuevo)) {
            JOptionPane.showMessageDialog(this, "Producto agregado correctamente");
            panelPadre.cargarProductos();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar producto");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JComboBox<Categoria> jCbxCategoriaProd;
    private javax.swing.JLabel jLblCategoriaProd;
    private javax.swing.JLabel jLblDescripcionProd;
    private javax.swing.JLabel jLblNombreProd;
    private javax.swing.JLabel jLblPrecioProd;
    private javax.swing.JLabel jLblStockProd;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPnlCategoriaProducto;
    private javax.swing.JPanel jPnlDescripcionProducto;
    private javax.swing.JPanel jPnlGuardarButton;
    private javax.swing.JPanel jPnlMain;
    private javax.swing.JPanel jPnlNombreProducto;
    private javax.swing.JPanel jPnlPrecioProducto;
    private javax.swing.JPanel jPnlStockProducto;
    private javax.swing.JPanel jPnlTitle;
    private javax.swing.JTextField jTxFDescripcionProd;
    private javax.swing.JTextField jTxFNombreProd;
    private javax.swing.JTextField jTxFPrecioProd;
    private javax.swing.JTextField jTxFStockProd;
    // End of variables declaration//GEN-END:variables
}
