/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.productos;

/**
 *
 * @author luish
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form asdsad
     */
    public Productos() {
        initComponents();
        inicializarSubpaneles();
    }

    private void inicializarSubpaneles() {
        removeAll();

        // ===================== SubPanelLogin1 =====================
        SubPanelProductos1 = new vista.productos.SubPanelProductos1(); // 
        setLayout(new java.awt.BorderLayout());
        add(SubPanelProductos1, java.awt.BorderLayout.CENTER);

        // Refrescar layout
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubPanelProductos1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout SubPanelProductos1Layout = new javax.swing.GroupLayout(SubPanelProductos1);
        SubPanelProductos1.setLayout(SubPanelProductos1Layout);
        SubPanelProductos1Layout.setHorizontalGroup(
            SubPanelProductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SubPanelProductos1Layout.setVerticalGroup(
            SubPanelProductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(SubPanelProductos1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubPanelProductos1;
    // End of variables declaration//GEN-END:variables
}
